/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package abilb.problems;


import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class AppTest {
    @Test public void testAppHasAGreeting() {        
        App classUnderTest = new App();
        assertNotNull( classUnderTest.getGreeting(), "app should have a greeting" );
    }
}
